Accessibility
CodeAllianceOrg/odk2 pull request #16
Opened 2017-10-31 14:56 UTC by bripc

2017-10-31 17:03 UTC, russon77 commented on src/app/form-builder/form-builder.component.html
> +  <!-- TODO: these should only appear when a section is available to add to -->
please move TODOs to Github issues! that way we can't forget about them :-)

2017-10-31 17:04 UTC, russon77 commented on src/app/form-builder/form-builder-properties/form-builder-properties.component.html
> +      <legend>Machine Readable Name</legend>
by "Base" i meant the __base__ item properties, which I think we should adapt to "Base Properties"

2017-10-31 17:05 UTC, russon77 commented on src/app/form-builder/form-builder-properties/form-builder-properties.component.html
> +      <label class="sr-only" for="item-name">Item Name</label>
please restore the always visible label along with the change to the legend

2017-10-31 17:06 UTC, russon77 commented on src/app/form-builder/form-builder-groups/form-builder-groups.component.html
> +      </ul>
i disagree with the change here. i'd like to keep the button group, maybe move to the button toolbar, as seen here https://getbootstrap.com/docs/4.0/components/button-group/ . according to bootstrap we can manage with accessibility okay!

2017-10-31 17:06 UTC, tristanmkernan requested changes
looking good, the copy changes are great and the issues are minor!

2017-11-06 15:19 UTC, closed without merging

2017-11-06 15:22 UTC, russon77 commented
@bripc in the interest of time i have made the appropriate changes and merged the code. nice work!